[package]
name = "sequexa-core"
version = "0.1.0"
edition = "2024"
description = "A sequential model engine in Rust with a built-in autograd engine, built on wilupgu."
license = "MIT OR Apache-2.0"
repository = "https://github.com/superroket169/sequexa-core"
readme = "README.md"
keywords = ["autograd", "transformer", "machine-learning", "gpu", "wgpu"]
categories = ["science"]
include = ["src/**", "Cargo.toml", "LICENSE-*", "README.md"]

[dependencies]
wilupgu = { path = "../wilupgu" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
pollster = "0.3"
bytemuck = { version = "1.15", features = ["derive", "extern_crate_alloc"] }
rand = "0.8"
tokenizers = { version = "0.19", features = ["http"] }
parquet = { version = "59.2.0", default-features = false, features = ["snap", "zstd"] }

[features]
default = ["vulkan"]
vulkan = ["wilupgu/vulkan"]
cuda = ["wilupgu/cuda"]
cpu = ["wilupgu/cpu"]
